//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginAttempt
    {
        public int Id { get; set; }
        public string Username_fk { get; set; }
        public Nullable<int> Attempt { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<bool> Blocked { get; set; }
    
        public virtual User User { get; set; }
    }
}
